title: 'Form: Search'
handle: form_search
status: ready
variants:
  - name: Small
    context:
      theme: sm
      show_label: false
      term: City Clerk
  - name: Medium
    context:
      theme: md
      show_label: false
      term: City Clerk
  - name: Yellow
    context:
      theme: y

context:
  show_label: true
