title: Base
handle: base
status: wip
context:
  links:
    - name: Public Notices
      href: https://boston.gov/public-notices
    - name: Pay and Apply
      href: https://boston.gov/pay-and-apply
    - name: Feedback
      href: https://boston.gov/feedback
  menu_links:
    - name: Help/311
      href: https://boston.gov/311
      theme: y
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
    - name: Programs and Initiatives 6
      href: https://boston.gov/feedback
      has_kids: true
      links:
        - name: Programs and Initiatives 2
          href: https://boston.gov/feedback
        - name: Programs and Initiatives 3
          href: https://boston.gov/feedback
        - name: Programs and Initiatives 4
          href: https://boston.gov/feedback
        - name: Programs and Initiatives 5
          href: https://boston.gov/feedback
    - name: Programs and Initiatives 10
      href: https://boston.gov/feedback
      has_kids: true
      links:
        - name: Programs and Initiatives 12
          href: https://boston.gov/feedback
        - name: Programs and Initiatives 13
          href: https://boston.gov/feedback
        - name: Programs and Initiatives 14
          href: https://boston.gov/feedback
        - name: Programs and Initiatives 15
          href: https://boston.gov/feedback
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
    - name: Programs and Initiatives
      href: https://boston.gov/feedback
