title: Address
handle: address
status: ready
context:
  address:
    thoroughfare: 'Boston City Hall, Room #241'
    thoroughfare2: '2nd floor'
    premise: '1 City Hall Square'
    locality: 'Boston'
    state: 'MA'
    postal_code: '02201'
